grafana/loki-release

- actions/get-version.ts
The release candidate part of the version is appended with a `-` not a `.`
> fix: get version release candidate

- .github/workflows/release.yml
- workflows/release.libsonnet
Still using hardcoded loki bucket when downloading images, this fixes that step to use the env var.
> fix: use correct bucket when downloading images

- .github/workflows/release-pr.yml
- .github/workflows/test-release-pr.yml
- workflows/build.libsonnet
- workflows/common.libsonnet
added cleanup step to remove 9GB of cache before running `dist` stage.
[Prepare Patch Release PR](https://github.com/grafana/loki/actions/workflows/patch-release-pr.yml) is constantly failing with an error: `no space left on device` ([example](https://github.com/grafana/loki/actions/runs/10299080044/job/28508736330)). 
I found the Github mounts a special folder(cache) with all supported versions of Python, Node, Go, etc, which are used when `Setup Go/Python/etc` action is used ([see](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#specifying-a-python-version)). 
**For the jobs that are executed inside loki-build-image, this cache is not needed at all....**
We could gain free space to win the time until we refactor/redesign our release workflow. …
> fix: added cleanup step before running `dist` stage.

- .github/workflows/release-pr.yml
- .github/workflows/test-release-pr.yml
- workflows/build.libsonnet
When running `make release-workflows` in enterprise-logs, the version of `docker/build-push-action` was downgraded from v6 to v5.
> chore: Update docker/build-push-action to v6

- .github/workflows/check.yml
- .github/workflows/gel-check.yml
- .github/workflows/release-pr.yml
- .github/workflows/test-release-pr.yml
- workflows/main.jsonnet
Updates Go to 1.23.1
Includes an update to golangci, which supports Go 1.23
> chore: Move to Go 1.23.1 along with updated golangci

- .github/workflows/check.yml
- workflows/validate.libsonnet
https://github.com/grafana/loki/pull/14456 move the `golangci-lint` build tags to runtime arguments, which will require this change to the `golangci-lint` action
> feat: specify golangci-lint build tags at runtime

- .github/workflows/release-pr.yml
- .github/workflows/test-release-pr.yml
- workflows/build.libsonnet
- workflows/runner.libsonnet
This pull request changes the way how multi-arch images are built. Instead of cross-compiling on emulated architecture using multiple platforms in the docker buildx build command, it uses dedicated arm and amd runners to build images "natively" and later combining the resulting image digests into a multi-arch manifest.
Example of a successful workflow run: https://github.com/grafana/loki/actions/runs/12907676490
> chore: Build docker images on runner arch

- actions/install-binary/dist/index.js
- actions/push-images/__tests__/docker.test.ts
- actions/push-images/dist/index.js
- actions/push-images/src/docker.ts
- actions/push-images/src/main.ts
A fix for not publishing the `latest` releases to Dockerhub.  While creating and publishing Docker/plugin images, if the `isLatest` is set to `true`, we also create a `latest` tag and push that.
> chore(build): Pass isLatest to code that does Docker things

- workflows/main.jsonnet
We don't want to publish the docker driver in the GEL build
> feat: allow GEL to skip docker pluging publishing

- actions/should-release/__tests__/release.test.ts
- actions/should-release/src/github.ts
- actions/should-release/src/release.ts
Latest workflow [run](https://github.com/grafana/loki/actions/runs/13283607213/job/37087375911) did not find `3.4.0` to be latest, due to the helm tags in the repository.  This restricts the lookup to be only loki (`vx.y.z`) tags.
> chore(build): Restrict tag version handling to be loki tags

- .github/workflows/check.yml
- workflows/validate.libsonnet
Inspired by https://github.com/grafana/loki/actions/runs/13420886614/job/37492970200?pr=16376, which showed the Loki shellcheck linting running against release code because it was being run from the root of the action pod workspace.
> fix: correct scope of loki make targets

- .github/workflows/release-pr.yml
- .github/workflows/test-release-pr.yml
- workflows/build.libsonnet
- workflows/install_workflow_dependencies.sh
Previously, the `dist` step was failing in GEL due to the removal of the enterprise-logs-build-image.  The new build image (a `golang` container) did not have fpm support.
Failing run: https://github.com/grafana/enterprise-logs/actions/runs/13446671228/job/37574044281
This PR updates the `dist` step to run the `install_workflow_dependencies.sh` script to install the needed items.  That script has also been enhanced to take a parameter, `dist`, that when provided, will install tooling only needed for the `dist` step (rpm, fpm, etc).  Longer term, we may want to tune this script to have even more granularity, but that is beyond the scope of this exercise.  
Furthermore, it is set to make this dependency installation optional, based on the build image provided.  This way, Loki, which uses …
> fix(build): Fix for the dist step

- .github/workflows/check.yml
- workflows/validate.libsonnet
A mistake in the jsonnet was overwriting the working directory for the `testLambdaPromtail` and `testPushPackage` tests, causing them to be run from the root directory, effectively running ALL THE TESTS in Loki 😱 
This fixes that.
> fix: remove redundant tests

- .github/workflows/check.yml
- workflows/validate.libsonnet
The Ci is failing: https://github.com/grafana/loki/actions/runs/14230955463/job/39881345947
Running go mod tidy locally doesn't yield any change, so we are adding it as a step to the failing workflow.
> fix: Add go mod tify step to testPushPackage

- .github/workflows/check.yml
- workflows/workflows.jsonnet
Follow on PR to https://github.com/grafana/loki-release/pull/233
Removes hardcoded library reference, now that the scripts are in `main`
> chore(build): Remove hardcoded workflow library reference

- .github/workflows/release-pr.yml
- .github/workflows/release.yml
- .github/workflows/test-release-pr.yml
- workflows/common.libsonnet
- workflows/main.jsonnet
- workflows/workflows.jsonnet
Setting the github app name configurable as environment variable to be used in multiple repos with different app names.
> ci: set github app as environment variable

- .github/workflows/check.yml
- .github/workflows/gel-check.yml
- .github/workflows/release-pr.yml
- .github/workflows/release.yml
- .github/workflows/test-release-pr.yml
- workflows/release.libsonnet
Pulls in latest fixes from `main` from the last few days.
> chore(ci): Pull in latest fixes from main into 2.9 flow

- .github/workflows/release.yml
- workflows/release.libsonnet
publish docker plugins needs to login to docker, which requires vault, which require `id-token: write`
> fix: publishing docker plugins needs the GHA token

- .github/workflows/check.yml
- workflows/validate.libsonnet
We want PRs to fail this check if the check on the target branch also fails.
> chore: Set `only-new-issues` in golangci-lint check to `false`

- .github/workflows/check.yml
- workflows/validate.libsonnet
We should use the new `stringlabels` since https://github.com/grafana/loki/pull/18490 was merged
> chore: Revert "refactor: Add slicelabels to check workflow (#265)"
